name: CI/CD Pipeline for Sentiment API

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rockyglen/sentiment-api:latest
          # A good practice is to also tag with the commit hash for versioning
          # tags: your_dockerhub_username/sentiment-api:latest, your_dockerhub_username/sentiment-api:${{ github.sha }}